[package]
name = "api"
version = "0.1.0"
authors = ["Sebastian Porto <s@porto5.com>"]

[dependencies]
bcrypt = "0.2"
chrono = "0.4"
chrono-tz = "0.4"
diesel = { version = "1.3", features = ["postgres", "chrono"] }
frank_jwt = "*"
juniper = "0.9.2"
juniper_codegen = "0.9.2"
juniper_rocket = "0.1.2"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
regex = "0.2.5"
rocket = "0.3.14"
rocket_codegen = "0.3.14"
rocket_cors = "0.2.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.7"
validator_derive = "0.7"

[dependencies.hashids]
git = "https://github.com/charsyam/hashids_rust.git"
version = "1.0.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[dev-dependencies]
fake = "*"
hamcrest = "*"
